language: node_js
sudo: false
node_js:
- '4'
cache:
  apt: true
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
env:
- CXX=g++-4.8
before_install:
  - git config --global user.name "janhuang"
  - git config --global user.email "384099566@qq.com"
  - git config --global push.default simple
script:
  - git clone https://${token}@github.com/JanHuang/janhuang.github.io.git .deploy_git
    -v
  - git --version
  - npm install --no-optional
after_script:
  - hexo generate && gulp
  - cp -r public/* .deploy_git/
  - cd .deploy_git
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force -q
branches:
  only:
  - master
